# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: ServiceAccount
metadata:
  name: search-ui
  labels:
    app: {{ .Values.search.name }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    component: search-ui
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}