---
dist: xenial
sudo: required
language: generic

   
os:
  - linux

services:
  - docker

stages:
  - build
  - auto
  - release-ff

branches:
  only:
    - main
    - /^release-[0-9]+\..*$/

jobs:
  include:
    - stage: build
      name: "Lint and Build"
      script:
        - make init
        - make lint
        - make copyright-check
        - make build
    - stage: auto
      name: "Auto trigger mch-repo"
      if: type = push AND branch =~ /^release-[0-9]+\..*$/
      script: 
        - git clone --single-branch --branch main https://${MCH_REPO_BOT_TOKEN}@github.com/open-cluster-management/multicloudhub-repo.git
        - cd multicloudhub-repo
        - ./cicd-scripts/chartAutomation.sh search-chart
    - stage: release-ff
      name: "Push commits to current release branch"
      if: type = push AND branch =~ /^main$/
      script:
        - make
        - make release-ff

