---
dist: xenial
sudo: required
language: generic

   
os:
  - linux

services:
  - docker

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/


before_script:
  - make init
  - make lint

script:
  - make copyright-check
  - make build

stages:
  - name: auto
  if: branch = newAuto
  script:
    make auto