---
dist: xenial
sudo: required
language: generic

   
os:
  - linux

services:
  - docker

stages:
  - build
  - auto

jobs:
  include:
    - stage: build
      name: "Lint and Build"
      script:
        - make init
        - make lint
        - make copyright-check
        - make build
    - stage: auto
      name: "Auto trigger mch-repo"
      if: type = push AND branch =~ /^master$/
      script: 
        - git clone --single-branch --branch master https://${MCH_REPO_BOT_TOKEN}@github.com/open-cluster-management/multicloudhub-repo.git
        - cd multicloudhub-repo
        - ./cicd-scripts/chartAutomation.sh search-chart
