---
dist: xenial
sudo: required
language: generic

   
os:
  - linux

services:
  - docker

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/


before_script:
  - make tool
  - make lint

script:
  - make build
