---
dist: xenial
sudo: required
language: generic


before_install:
  - source travis-env.sh
   
install:
  - docker info

os:
  - linux

services:
  - docker

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/


before_script:
  - make tool
  - make init
  - make lint

script:
  - make build
