---
dist: xenial
sudo: required
# group: bluezone
language: generic

# Environment variables (setup endpoint to IBM github)
env:
  global:
  - OCTOKIT_API_ENDPOINT="https://github.ibm.com/api/v3/"

before_install:
  - source travis-env.sh
   
install:
  - docker info


os:
  - linux

services:
  - docker

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/


before_script:
  - make tool
  - make init
  - make lint

script:
  - make build
