---
dist: xenial
sudo: required
language: generic

   
os:
  - linux

services:
  - docker

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/


before_script:
  - make init
  - make lint

script:
  - make copyright-check
  - make build

stages:
 - auto

jobs:
  include:
    - stage: auto
      name: "Auto trigger mch-repo"
      if: type = pull_request
      script: 
        - git clone --single-branch --branch dev-auto https://${MCH_REPO_BOT_TOKEN}@github.com/open-cluster-management/multicloudhub-repo.git
        - cd multicloudhub-repo
        - ./cicd-scripts/chartAutomation.sh search-chart