---
dist: xenial
sudo: required
language: generic

   
os:
  - linux

services:
  - docker

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/


before_script:
  - make init
  - make lint

script:
  - make copyright-check
  - make build

deploy: 
  provider: script
  script: 
    - "make auto"
  true: 
    branch: newAuto