# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:addons:search-collector
rules:
  - verbs:
      - create
    apiGroups:
      - proxy.open-cluster-management.io
    resources:
      - clusterstatuses/aggregator
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - patch
      - update
      - watch
      - create
