# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.org }}:{{ .Release.Name }}:search-aggregator
rules:
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclusters"]
  verbs:
  - get
  - list
  - watch
- apiGroups: ['internal.open-cluster-management.io']
  resources: ["managedclusterinfos"]
  verbs:
  - get
  - list
  - watch
- apiGroups: ["search.open-cluster-management.io"]
  resources: ["searchoperators"]
  verbs:
  - get