# Copyright (c) 2020 Red Hat, Inc.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.org }}:{{ .Release.Name }}:search-aggregator
rules:
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclusters"]
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: search-aggregator
rules:
- apiGroups: ['internal.open-cluster-management.io']
  resources: ["managedclusterinfos"]
  verbs:
  - get
  - list
  - watch
