# Copyright (c) 2020 Red Hat, Inc.

apiVersion: v1
kind: ConfigMap
metadata:
  name: search-aggregator
  labels:
    config: mcm-aggregator
data:
  service: search-aggregator
  port: "3010"
  path: "/aggregator/clusters/"
  sub-resource: "/sync"
  use-id: "true"
  secret: "{{ .Release.Namespace }}/search-aggregator-secrets"