# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: ConfigMap
metadata:
  name: search-aggregator
  labels:
    config: acm-proxyserver
data:
  service: "{{ .Release.Namespace }}/search-aggregator"
  port: "3010"
  path: "/aggregator/clusters/"
  sub-resource: "/sync"
  use-id: "true"
  secret: "{{ .Release.Namespace }}/search-aggregator-secrets"
  caConfigMap: search-ca-crt