# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "search.fullname" . }}-search-api
  labels:
    app: {{ .Values.search.name }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    component: "search-api"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.hubconfig.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.search.name }}
      component: "search-api"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.search.name }}
        ocm-antiaffinity-selector: "searchapi"
        component: "search-api"
        release: {{ .Release.Name }}
        chart: {{.Chart.Name}}-{{.Chart.Version}}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: search-api
      securityContext:
          runAsNonRoot: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                {{- range .Values.global.arch }}
                - {{ . }}
                {{- end }}
        {{- with .Values.api.affinity.podAntiAffinity }}
        podAntiAffinity: 
{{ toYaml . | indent 10 }}
        {{- end }}
      tolerations:
        - key: dedicated
          operator: Exists
          effect: NoSchedule
        - effect: NoSchedule 
          key: node-role.kubernetes.io/infra 
          operator: Exists
      containers:
      - name: search-api
        image: {{ .Values.global.imageOverrides.search_api }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        env:
        - name: cfcRouterUrl
          value: {{ .Values.global.cfcRouterUrl }}
        - name: PLATFORM_IDENTITY_PROVIDER_URL
          value: {{ .Values.global.cfcRouterUrl }}/idprovider
        - name: redisSSLEndpoint
          value: '{{ template "search.fullname" . }}-search-redisgraph.{{ .Values.org }}.svc:6380'
        - name: redisPassword
          valueFrom:
            secretKeyRef:
              name: redisgraph-user-secret
              key: redispwd
        ports:
        - containerPort: 4010
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livenessProbe
            port: 4010
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readinessProbe
            port: 4010
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.search.searchapi.resources | indent 10 }}
        volumeMounts:
        - name: search-api-certs
          mountPath: /opt/app-root/search-api/sslcert
        - name: redis-graph-certs
          mountPath: /opt/app-root/search-api/rediscert/redis.crt
          subPath: redis.crt
      hostIPC: false
      hostNetwork: false
      hostPID: false
      {{- if .Values.global.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.pullSecret }}
      {{- end }}
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      - name: search-api-certs
        secret:
          secretName: {{ .Release.Name }}-search-api-secrets
          items:
          - key: tls.crt
            path: searchapi.crt
          - key: tls.key
            path: searchapi.key
      - name: redis-graph-certs
        configMap:
          name: search-redis-ca-crt
          items:
            - key: service-ca.crt
              path: redis.crt
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}
