# Copyright (c) 2020 Red Hat, Inc.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: search-api
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: search-api
rules:
- apiGroups: ["console.open-cluster-management.io"]
  resources: ["userpreferences"]
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups: ["open-cluster-management.io"]
  resources: ["managedclusteractions", "managedclusterviews"]
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups: ["project.openshift.io"]
  resources: ["projects"]
  verbs:
  - get
  - list
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs:
  - get
  - create
  - delete
