# Copyright (c) 2020 Red Hat, Inc.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: search-api
rules:
- apiGroups: ["console.open-cluster-management.io"]
  resources: ["userpreferences"]
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups: ["project.openshift.io"]
  resources: ["projects"]
  verbs:
  - get
  - list
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
  verbs:
  - get
  - list
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs:
  - get
  - create
  - delete
