kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.org }}:{{ .Chart.Name }}:search-collector
subjects:
- kind: ServiceAccount
  name: search-collector
  namespace: {{ .Release.Namespace }} 
roleRef:
  kind: ClusterRole
  name: {{ .Values.org }}:{{ .Chart.Name }}:search-collector
  apiGroup: rbac.authorization.k8s.io
