# Copyright (c) 2020 Red Hat, Inc.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: search-operator
{{- if .Values.global.pullSecret }}
imagePullSecrets:
- name: {{ .Values.global.pullSecret }}
{{- end }}
