# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: search-operator
  template:
    metadata:
      labels:
        name: search-operator
        ocm-antiaffinity-selector: "searchoperator"
    spec:
      serviceAccountName: search-operator
      tolerations:
      - effect: NoSchedule 
        key: node-role.kubernetes.io/infra 
        operator: Exists
      affinity:
        {{- with .Values.collector.affinity.podAntiAffinity }}
        podAntiAffinity: 
{{ toYaml . | indent 10 }}
        {{- end }}
      containers:
      - name: search-operator
        args:
        - --enable-leader-election
        command: ["/manager"]
        image: {{ .Values.global.imageOverrides.search_operator }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        env:
          - name: RELEASE_NAME
            value: {{ .Release.Name }}
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "search-operator"
        resources:
{{ toYaml .Values.search.operator.resources | indent 10 }}
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}
