# Copyright (c) 2020 Red Hat, Inc.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: search-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - helmreleases
  verbs:
  - get
- apiGroups:
  - "search.acm.com"
  - "search.open-cluster-management.io"
  resources:
  - searchservices
  - searchservices/finalizers
  verbs:
  - create
  - list
  - watch
  - update
