# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.


apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "search.fullname" . }}-redis-secret-job
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "search.fullname" . }}-redis-secret-job
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": "-4"
spec:
  template:
    metadata:
      name: {{ template "search.fullname" . }}-redis-secret-job
      labels:
        app: {{ template "search.fullname" . }}-redis-secret-job
        chart: {{.Chart.Name}}-{{.Chart.Version}}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                {{- range .Values.global.arch }}
                - {{ . }}
                {{- end }}
      tolerations:
        - key: dedicated
          operator: Exists
          effect: NoSchedule
      containers:
        - name: kubectl
          image: "{{ .Values.kubectl.repository }}:{{ .Values.kubectl.tag }}"
          imagePullPolicy: "{{ .Values.kubectl.pullPolicy }}"
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
              - ALL
          command:
          - /redisusersecret/create-secret.sh
          resources:
            requests:
              memory: "256Mi"
              cpu: "25m"
            limits:
              memory: "512Mi"
              cpu: "50m"
          volumeMounts:
          - mountPath: "/redisusersecret"
            name: redis-secret-config
      hostIPC: false
      hostNetwork: false
      hostPID: false
      restartPolicy: OnFailure
      {{- if .Values.global.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.pullSecret }}
      {{- end }}
      volumes:
      - name: redis-secret-config
        configMap:
          name: {{ template "search.fullname" . }}-create-redis-secret
          defaultMode: 0755
