# Copyright (c) 2020 Red Hat, Inc.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: search-redisgraph
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - patch
