apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: search-default2
  namespace: open-cluster-management
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - patch
