# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "search.fullname" . }}-search-ca-cert
  labels:
    app: {{ .Values.search.name }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    component: "search-api"
    heritage: {{ .Release.Service }}
spec:
  secretName: {{ .Release.Name }}-search-api-secrets
  issuerRef:
    name: {{ .Values.global.clusterCAIssuer }}
    kind: ClusterIssuer
  commonName: search-api
  dnsNames:
  - {{ template "search.fullname" . }}-search-api
  - {{ template "search.fullname" . }}-search-api.{{ .Release.Namespace }}
  - {{ template "search.fullname" . }}-search-api.{{ .Release.Namespace }}.svc
  isCA: true
  organization:
  - Red Hat
