apiVersion: search.open-cluster-management.io/v1
kind: SearchOperator
metadata:
  name: searchoperator
spec:
  persistence: true
  allowdegrademode: true
  storagesize: 10Gi
  pullpolicy: {{ .Values.global.pullPolicy }}
  searchimageoverrides:
    redisgraph_tls: {{ .Values.global.imageOverrides.redisgraph_tls }}
  {{- if .Values.global.pullSecret }}
  pullsecret: {{ .Values.global.pullSecret }}
  {{- end }}
  redisgraph_resource:
    limit_cpu: {{ toYaml .Values.search.redisgraph.resources.limits.cpu }}
    limit_memory: {{ toYaml .Values.search.redisgraph.resources.limits.memory }}
    request_cpu: {{ toYaml .Values.search.redisgraph.resources.requests.cpu }}
    request_memory: {{ toYaml .Values.search.redisgraph.resources.requests.memory }}
    
  
