# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.open-cluster-management.io/auth-type: access-token
    kubernetes.io/ingress.class: ingress-open-cluster-management
  name: search-ui
  labels:
    app: {{ .Values.search.name }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    component: search-ui
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
  - http:
      paths:
      - path: /search
        pathType: ImplementationSpecific
        backend:
          service:
            name: search-ui
            port:
              number: 3000
      - path: /overview
        pathType: ImplementationSpecific
        backend:
          service:
            name: search-ui
            port:
              number: 3000
      - path: /resources
        pathType: ImplementationSpecific
        backend:
          service:
            name: search-ui
            port:
              number: 3000
      - path: /multicloud/search
        pathType: ImplementationSpecific
        backend:
          service:
            name: search-ui
            port:
              number: 3000
      - path: /multicloud/overview
        pathType: ImplementationSpecific
        backend:
          service:
            name: search-ui
            port:
              number: 3000
      - path: /multicloud/details
        pathType: ImplementationSpecific
        backend:
          service:
            name: search-ui
            port:
              number: 3000