# Copyright (c) 2020 Red Hat, Inc.

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.org }}:{{ .Release.Name }}:search-ui
subjects:
- kind: ServiceAccount
  name: search-ui
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.org }}:{{ .Release.Name }}:search-ui
  apiGroup: rbac.authorization.k8s.io