# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: {{ template "search.fullname" . }}-upgrade-deployments
#   namespace: {{ .Release.Namespace }}
#   annotations:
#     "helm.sh/hook": pre-upgrade,pre-install
#     "helm.sh/hook-delete-policy": hook-succeeded
#   labels:
#     app: {{ template "search.name" . }}
#     component: "search"
#     release: {{ .Release.Name }}
#     chart: {{ template "search.chart" . }}
#     heritage: {{ .Release.Service }}
# spec:
#   template:
#     metadata:
#       name: {{ template "search.fullname" . }}-upgrade-deployments
#       labels:
#         app: {{ template "search.name" . }}-upgrade-deployments
#         component: "search"
#         release: {{ .Release.Name }}
#         chart: {{ template "search.chart" . }}
#         heritage: {{ .Release.Service }}
#     spec:
#       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#             - matchExpressions:
#               - key: beta.kubernetes.io/arch
#                 operator: In
#                 values:
#                 {{- range .Values.global.arch }}
#                 - {{ . }}
#                 {{- end }}
#       tolerations:
#         - key: dedicated
#           operator: Exists
#           effect: NoSchedule
#       containers:
#         - name: kubectl
#           image: "{{ .Values.kubectl.repository }}:{{ .Values.kubectl.tag }}"
#           imagePullPolicy: "{{ .Values.kubectl.pullPolicy }}"
#           securityContext:
#             privileged: false
#             readOnlyRootFilesystem: false
#             allowPrivilegeEscalation: false
#             runAsNonRoot: true
#             runAsUser: 1000
#             capabilities:
#               drop:
#               - ALL
#           command:  ["/bin/bash","-c","kubectl delete deployment -l 'component in (mcm-search,search-aggregator,redisgraph)'" ]
#           resources:
#             requests:
#               memory: "64Mi"
#               cpu: "25m"
#             limits:
#               memory: "512Mi"
#               cpu: "50m"
#       hostIPC: false
#       hostNetwork: false
#       hostPID: false
#       restartPolicy: OnFailure
#       {{- if .Values.global.pullSecret }}
#       imagePullSecrets:
#       - name: {{ .Values.global.pullSecret }}
#       {{- end }}
