# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

org: stolostron

global:
  pullPolicy: Always
  pullSecret: null
  arch:
  - amd64
  - ppc64le
  - s390x
  cfcRouterUrl: "https://management-ingress:443"
  certificateAuthority:
    issuer: multicloud-ca-issuer
    kind: Issuer
  imageOverrides:
    redisgraph_tls: ""
    search_aggregator: ""
    search_api: ""
    search_collector: ""
    search_operator: ""

ocpingress: ""
    
hubconfig:
  nodeSelector: null
  replicaCount: 1

api:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 70
        podAffinityTerm:
          topologyKey: topology.kubernetes.io/zone
          labelSelector:
            matchExpressions:
            - key: ocm-antiaffinity-selector
              operator: In
              values:
              - searchapi
      - weight: 35
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
            - key: ocm-antiaffinity-selector
              operator: In
              values:
              - searchapi

aggregator:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 70
        podAffinityTerm:
          topologyKey: topology.kubernetes.io/zone
          labelSelector:
            matchExpressions:
            - key: ocm-antiaffinity-selector
              operator: In
              values:
              - searchaggregator
      - weight: 35
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
            - key: ocm-antiaffinity-selector
              operator: In
              values:
              - searchaggregator
  
collector:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 70
        podAffinityTerm:
          topologyKey: topology.kubernetes.io/zone
          labelSelector:
            matchExpressions:
            - key: ocm-antiaffinity-selector
              operator: In
              values:
              - searchcollector
      - weight: 35
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
            - key: ocm-antiaffinity-selector
              operator: In
              values:
              - searchcollector

operator:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 70
        podAffinityTerm:
          topologyKey: topology.kubernetes.io/zone
          labelSelector:
            matchExpressions:
            - key: ocm-antiaffinity-selector
              operator: In
              values:
              - searchoperator
      - weight: 35
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
            - key: ocm-antiaffinity-selector
              operator: In
              values:
              - searchoperator

search:
  name: search
  aggregator:
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "1024Mi"
  collector:
    resources:
      requests:
        memory: "64Mi"
        cpu: "25m"
      limits:
        memory: "768Mi"
  searchapi:
    resources:
      requests:
        memory: "128Mi"
        cpu: "25m"
      limits:
        memory: "1024Mi"
  redisgraph:
    resources:
      requests:
        memory: "128Mi"
        cpu: "25m"
      limits:
        memory: "4Gi"
  operator: 
    resources:
      requests:
        memory: "32Mi"
        cpu: "1m"
      limits:
        memory: "256Mi"
