# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.


search:
  name:
    type: string
  fullname:
    type: string
  __metadata:
    label: "Multicloud Search Service"
    description: "Configuration for Multicloud Manager Search Service"
  aggregator:
    image:
      pullPolicy:
        __metadata:
          label: "Search-aggregator Image Pull Policy"
          description:  "Image Pull Policy for Search-aggregator"
          type: "string"
          required: false
          options:
          - label: "IfNotPresent"
            value: "IfNotPresent"
          - label: "Always"
            value: "Always"
          - label: "Never"
            value: "Never"
    resources:
      requests:
        memory:
          type: "string"
        cpu:
          type: "string"
      limits:
        memory:
          type: "string"
        cpu:
          type: "string"
  collector:
    image:
      pullPolicy:
        __metadata:
          label: "Search-collector Image Pull Policy"
          description:  "Image Pull Policy for Search-collector"
          type: "string"
          required: false
          options:
          - label: "IfNotPresent"
            value: "IfNotPresent"
          - label: "Always"
            value: "Always"
          - label: "Never"
            value: "Never"
    resources:
      requests:
        memory:
          type: "string"
        cpu:
          type: "string"
      limits:
        memory:
          type: "string"
        cpu:
          type: "string"
  redisgraph:
    image:
      pullPolicy:
        __metadata:
          label: "RedisGraph Image Pull Policy"
          description:  "Image Pull Policy for RedisGraph"
          type: "string"
          required: false
          options:
          - label: "IfNotPresent"
            value: "IfNotPresent"
          - label: "Always"
            value: "Always"
          - label: "Never"
            value: "Never"
    resources:
      requests:
        memory:
          type: "string"
        cpu:
          type: "string"
      limits:
        memory:
          type: "string"
        cpu:
          type: "string"
  searchapi:
    image:
      pullPolicy:
        __metadata:
          label: "Search-api Image Pull Policy"
          description:  "Image Pull Policy for Search-api"
          type: "string"
          required: false
          options:
          - label: "IfNotPresent"
            value: "IfNotPresent"
          - label: "Always"
            value: "Always"
          - label: "Never"
            value: "Never"
    resources:
      requests:
        memory:
          type: "string"
        cpu:
          type: "string"
      limits:
        memory:
          type: "string"
        cpu:
          type: "string"

kubectl:
  __metadata:
    label: "kubectl pod config"
    description: "Configuration for kubectl deployment"
  repository:
    type: string
  name:
    type: string
  tag:
    type: string
  pullPolicy:
    options:
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"

global:
  arch:
    type: options
  cfcRouterUrl:
    type: string
  certificateAuthority:
    issuer:
      __metadata:
        label: "Certificate Authority Issuer"
        description: "CA to sign the certificates for the search services"
        type: string
    kind:
      __metadata:
        label: "Certificate Issuer Kind"
        description: "Kind of certificate issuer (ClusterIssuer or Issuer)"
        type: string
  nodeSelector:
    os:
      type: string
    customLabelValue:
      type: string
    customLabelSelector:
      type: string
    enabled:
      type: boolean
  __metadata:
    label: "Global Settings for Search"
    description: "Global Settings for Search Chart Deployment"
  pullSecret:
    __metadata:
      label: "Docker Registry Authentication"
      description: "Secret of Docker Authentication"
      type: "string"
      immutable: false
      required: false
  tillerIntegration:
    user:
      __metadata:
        label: "Tiller Username"
        description: "Username to tls connect Tiller from Hub"
        type: "string"
        immutable: false
        required: true
